### ISSUE TITLE
Bug feuille nage world guard 

### ISSUE THREAD

**Issue by Obonej** [Paladium-Developpement/Paladium-Bedrock-Issues#100]
### Minecraft Username

Obonej

### Description of the bug

En gros quand on case un feuillage dans la zone protégée du spawn et que notre personnage est juste devant cela agit comme une trapdoor par exemple ce qui permet de passer en dessous par exemple

**Comment by Chaika9** [comment]
Salut, c'est compliqué à corriger comme problème, car c'est un lag entre le moment où tu casses le bloc et que le serveur confirme.
