### ISSUE TITLE
[Bug] Impossibilité de fermer le four

### ISSUE THREAD

**Issue by Obonej** [Paladium-Developpement/Paladium-Bedrock-Issues#101]
### Minecraft Username

Obonej

### Description of the bug

Si l'icone de votre souris est dans l'interface du four la touche échap ne fonctionne pas en revanche si l'icone de la souris est en dehors du four la touche échap fonctionne correctement.

**Comment by natof** [comment]
Ceci est normal four en Vanilla. Il est impossible de fermer l'interface avec la touche Échap si le curseur de la souris est sur un emplacement.
