### ISSUE TITLE
[Suggestion] Retirer la position des autres joueurs sur les mini maps

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Bedrock-Issues#107]
### Minecraft Username

Bl0ckgu01

### Description of your suggestion

Lorsqu'on a un carte (ex : carte au trésor), on voit les autres joueurs sur la carte et je pense c'est un peu abusé si on veut piller

**Comment by Chaika9** [comment]
Je ferme pour duplication (il y a deja une issue exisante)
