### ISSUE TITLE
[Suggestion] Masquer/Démasquer coordonnées dans les interfaces

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Paladium-Bedrock-Issues#112]
### Minecraft Username

pshyco9473

### Description of your suggestion

Il est possible de masquer les coordonnées lorsque l'on joue et c'est très pratique pour les personne qui veulent faire des lives. 
Cependant, dans l'interface des homes les coordonnées des homes sont affichées. Il faudrait, si possible, rajouter une option qui permet de masquer les coordonnées dans les interfaces (je ne sais pas si il y aura d'autres interfaces avec des coordonnées).

**Comment by Chaika9** [comment]
C'est deja le cas avec la commande /coords
