### ISSUE TITLE
[Suggestion] Plante qui pousse beaucoup trop vite

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Bedrock-Issues#116]
### Minecraft Username

SK0R3N

### Description of the bug

Les plantes prennent environ 1m30 a pouser sans totem, contrairement a java qui peuvent prendre plusieurs minutes sans totem.
Ça fait perdre l'utilité au totem des plantes qui pousse aussi vite.

https://youtu.be/rbTc4QTlCK8

**Comment by Chaika9** [comment]
Ce n'ai pas un bug, ducoup je déplace ca en suggestion. Il est prévu une reviste du GameDesign.
