### ISSUE TITLE
[Bug] : Taux drop des graines pas à 100%

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Bedrock-Issues#117]
### Minecraft Username

SK0R3N

### Description of the bug

Contrairement à Java , les plantes lorsqu'elles sont full poussés n'ont pas 100% de chance ce redropper une seed.

https://youtu.be/5-VO-TG1PvA

**Comment by Chaika9** [comment]
Video indisponible, si possible précise le comportement qui devrai avoir.
