### ISSUE TITLE
[Bug Jobs] Interface redirection

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Paladium-Bedrock-Issues#136]
### Minecraft Username

pshyco9473

### Description of the bug

Quand on appuie sur le level (lvl 2 sur l'image) l'interface se ferme et n'en n'ouvre pas d'autre

![image](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/110596782/21180bc6-c95e-4be0-aea4-efb0dee1f61d)

**Comment by Chaika9** [comment]
Bonjour, c'est normal, ce n'ai aps encore implementé sur la Beta.
