### ISSUE TITLE
[Bug Jobs] Xp infini

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Paladium-Bedrock-Issues#140]
### Minecraft Username

pshyco9473

### Description of the bug

En cassant un bloc (grante, andésite, stone, lapis lazuli, ,...) on gagne de l'xp pour le métier de mineur (comportement normal). Mais en reposant le bloc (déjà miné) et en le minant à nouveau on gagne encore de l'xp.

**Comment by Chaika9** [comment]
Acctuellement c'est un comportement normal
