### ISSUE TITLE
[Bug Jobs] Xp métier Miner : Cuisson iron

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Paladium-Bedrock-Issues#142]
### Minecraft Username

pshyco9473

### Description of the bug

J'ai passé le niveau en métier de miner.
Je ne gagne pas d'xp en faisant cuir le fer (si c'est le cas, le ``Miner + ??`` ne s'affiche pas)

**Comment by Chaika9** [comment]
Les XP par cuisson ne sont pas encore implémenté
