### ISSUE TITLE
[Bug] Pousse plante moddé : luminosité

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Paladium-Bedrock-Issues#145]
### Minecraft Username

pshyco9473

### Description of the bug

Les plantes moddées (chervil, eggplant, kiwano, orangeblue) pousse même quand il n'y a pas de luminosité sur une terre bêchée mais non fertilisée

**Comment by natof** [comment]
Sur Bedrock, malheureusement, ce n'est pas vraiment gérable côté add-on
