### ISSUE TITLE
[Bug]  Outils en Paladium impossible a craft

### ISSUE THREAD

**Issue by RaiiZou** [Paladium-Developpement/Paladium-Bedrock-Issues#150]
### Minecraft Username

RaiiZou4014

### Description of the bug

Bonjour/Bonsoir
Lorsqu'on tente de craft un outil en Paladium, le craft n'apparait pas sur la liste des crafts disponible et nous pouvons essayer de placer les ressources par nous même mais rien y fait, impossible de craft l'outil. Les armures elles, n'ont aucun problème.
![Liste des craft](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/0727ecea-3073-4a71-b2ff-adf7446c3897)
![Epee 1](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/edbf2b3d-b694-4c53-8c65-eb60882a47b3)
![Epee 2](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/5ef42cf1-5947-4915-a57b-2fd640dc3e5a)
![Epee 3](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/fa2f9ef5-f844-4014-8e74-a287edb2ee1a)
![Hache 1](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/2c1f611a-7857-4384-b526-1aca212edf09)
![Hache 2](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/ed30fa7f-fa73-47dd-933b-c64490843af1)
![Pelle 1](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/1cabd1a3-d0fb-4604-aadd-6a86618b8b02)
![Pelle 2](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/0f0a08d2-050b-46a4-a703-56c810fa1cbd)
![Pelle 3](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/f10f8568-ddde-4e54-b585-91edd27a1559)
![Pioche](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/9b3901e5-f306-43fc-9d33-0feaaac8a4fd)
![Plastron](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/83038640/ae86c14d-122a-4a29-9a08-36eab7c0178b)

**Comment by Katsun1236** [comment]
C'est normal, il te faudra tout d'abord craft un grinder (avec les blocks de l'image ci joint). Ensuite tu crafteras un paterne, chaque paterne te débloque une pièce de l'outil en paladium de ton choix, en posant du paladium dans ton grinder ainsi qu'en utilisant le paterne, tu pourras fabriqué ces pièces. 
Enfin il te suffira d'une palamachine pour crée ton outil avec 2 bâton de bois (ça va changer) et ta pièce d'outil en paladium
