### ISSUE TITLE
[Bug] Les membres d'une faction ne peuvent pas interagir dans les claims

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Bedrock-Issues#157]
### Minecraft Username

Bl0ckgu01

### Description of the bug

les membres d'une faction (hors chef de fac) ne peuvent détruire, placer et ouvrir des coffres comme si ils étaient pas dans la faction

**Comment by Chaika9** [comment]
Salut, ceci n'est pas un bug, c'est juste que les membres de ta faction n'ont pas de rôle avec la permission d'interagir dans les claims.
