### ISSUE TITLE
[Bug] Impossible de mettre des os dans un drawer

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Bedrock-Issues#164]
### Minecraft Username

Bl0ckgu01

### Description of the bug

Impossible de mettre des os dans un drawer (mais avec la bone meal ça fonctionne)

**Comment by Katsun1236** [comment]
Bonjour, je te confirme que si, il suffit de visé les rebord ou es cotés du drawer comme avec chaque item 
https://i.imgur.com/EAcsimt.png

**Comment by blockgu07** [comment]
c'est bizarre j'ai beau cliquer partout sur le drawer, ça fonctionne pas mais avec d'autres items si (d'ailleurs comment on a les améliorations de drawer ?)

**Comment by Katsun1236** [comment]
Tu pourrais envoyé un clip discord ? Et je t'ai répondu dans le channel bêta discussion

**Comment by blockgu07** [comment]
https://www.youtube.com/watch?v=Mzp87cOrV7s

**Comment by Chaika9** [comment]
Salut, ceci est normal, certains items son blacklist des drawers, les os ont fait partie.
