### ISSUE TITLE
[Bug] Cobblebreaker : Récupération de la stone 

### ISSUE THREAD

**Issue by Katsun1236** [Paladium-Developpement/Paladium-Bedrock-Issues#165]
### Minecraft Username

Katsun1246

### Description of the bug

Lorsque le cobblebreaker est détruit, il drop les particules contenu mais pas les block à détruire qu'il contient 
https://cdn.discordapp.com/attachments/1229099389784559646/1243985282873954364/Clip_-_25052024_195222.mp4?ex=66537713&is=66522593&hm=267cc5a0db29c321c05c3d5318d8aef869e33f1cde27513e31506a27415fb4a8&

**Comment by Chaika9** [comment]
Actuellement c'est normal au vu de la quantité possible qui peut être mis.
