### ISSUE TITLE
[Bug] Interraction graine moddé et barrière

### ISSUE THREAD

**Issue by Katsun1236** [Paladium-Developpement/Paladium-Bedrock-Issues#167]
### Minecraft Username

Katsun1246

### Description of the bug

Les barrière réagissent aux graines moddé comme si c'était des blocks, ce qui n'est pas le cas avec des graines classique
https://cdn.discordapp.com/attachments/1243985475853746176/1244013812252938280/image.png?ex=665391a5&is=66524025&hm=e27ca5ea709fe850000ce27194ee64800702d298974ae07ff47bb6e8037b9b4b&

**Comment by natof** [comment]
Malheureusement, c'est un bug non patchable de notre côté
