### ISSUE TITLE
[Bug] No XP cuissont minerais 

### ISSUE THREAD

**Issue by Katsun1236** [Paladium-Developpement/Paladium-Bedrock-Issues#170]
### Minecraft Username

Katsun1246

### Description of the bug

La cuisson des minerais (titane,paladium,paladium vert) ne rapporte pas d'expèrience au métier de mineur, en lien avec l'article de paladium ci-joint 
https://wiki.paladium-pvp.fr/les-metiers/mineur/evolution-du-metier

**Comment by Chaika9** [comment]
Déjà report, et déjà répondu comme quoi c'est normal.
