### ISSUE TITLE
[Bug] Bug xray

### ISSUE THREAD

**Issue by AngeDechue** [Paladium-Developpement/Paladium-Bedrock-Issues#29]
### Minecraft Username

pshyco9473

### Description of the bug

Je ne sais pas si c'est possible à fix mais il y a une méthode pour xray. Ça utilise un piston et de la neige.
Il y a une vidéo du bug

https://youtu.be/vDIBiwYEf0I

**Comment by Chaika9** [comment]
Salut, c'est un bug Client donc difficile à Patch de notre côté. Mais en sois c'est plus ce que ferait un cave bloc, donc pas très grave.

**Comment by AngeDechue** [comment]
Dacc c'était juste pour prévenir au cas où ^^
