### ISSUE TITLE
[Bug] Chaque coup enlève une dura

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Bedrock-Issues#33]
### Minecraft Username

SK0R3N

### Description of the bug

A chaque fois qu'on tappe un mob , on perd de la durabilité , certe comme ça c'est normal , mais on pert de la dura pendant le cooldown entre les hits. Dans le rec , au début je spam beaucoup ma souris et après je tappe seulement lors que mes coups vont marchés. On peut voir une différence au niveau de la durabilité

https://youtu.be/ZmaasncbNuo

**Comment by Chaika9** [comment]
Salut, la dessus c'est le fonctionnement de base de Minecraft Bedrock normal.

**Comment by SK0R3N** [comment]
Très bien , tu peux fermé l'issue si ça ne compte pas être changé.
