### ISSUE TITLE
[Bug] Paquet

### ISSUE THREAD

**Issue by Katsun1236** [Paladium-Developpement/Paladium-Bedrock-Issues#60]
### Minecraft Username

Katsun1246

### Description of the bug

Bug de paquet : 
Je suppose le bug, J'avais 3 block de tuff dans mon inventaire ou je ne pouvais les bouger et me bloquais une case de stockage. 
Il a fallu une reconnexion pour que le serveur actualise mon inventaire et comprenant que j'en avais 5 pour que je puisse à nouveau utiliser cette case de stockage. 
Je ne sais pas comment le reproduire.

**Comment by Chaika9** [comment]
Désolé, sans rec ca va être compliqué pour reproduire le problème.
Surtout que c'est peut être une erreur graphique (donc client)
