### ISSUE TITLE
[Bug] Restart du jeu

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#62]
### Minecraft Username

Legzo09

### Description of the bug

Lorsque votre jeu est en pleine écran, que vous changez de fenêtre sur votre ordinateur, puis que vous revenez sur le jeu, il redémarre et vous renvoie au menu principal de Minecraft. 

**Le problème, c'est qu'une texture est manquante à cause des chargements customs de connexion/déconnexion du serveur (Cf. Vidéo).**

https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/31188475-3c2d-43eb-bd0a-17dcaf08e1e8

**Comment by natof** [comment]
Si ton jeu est en plein écran et que tu fermes la fenêtre, le jeu se rechargera quand tu le rouvriras. Cela inclut également les packs. Si une texture semble manquante, c'est que Minecraft ne l'a pas encore chargée. C'est pareil pour les appareils mobiles

**Comment by natof** [comment]
Nan qu'a minecraft
