### ISSUE TITLE
[Bug] ClearLag : lama wandering trader

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#64]
### Minecraft Username

Legzo09

### Description of the bug

Les lamas des wandering traders ne sont pas affectés par le clearlag.
![Legzo - Lama_ClearLag](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/dfe993c5-aa96-4f10-80ee-9bd2d9509820)

**Comment by Legz0** [comment]
Note : je ne sais pas si les lamas classiques sont aussi dans le même cas

**Comment by Legz0** [comment]
Après vérification, non, c'est uniquement avec les wandering traders

**Comment by Chaika9** [comment]
Salut effectivement, ils sont considérés comme "apprivoisé" et donc ne sont pas clear.
Ca sera fix
