### ISSUE TITLE
[Bug] Furnace

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#65]
### Minecraft Username

Legzo09

### Description of the bug

Lorsque je clique sur ma touche 'echap' (lorsque la case d'inventaire sous ma souris et grise), cela ne me fait pas quitter la UI. Il faut que je clique sur ma touche parfois plusieurs dizaines de fois pour que je puisse sortir de l'interface. 

https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/dc49a7f4-88a8-427a-aab5-445b9fbb2636

**Comment by Chaika9** [comment]
Salut, ceci est un bug Minecraft de base, nous pouvons pas faire grand chose malheureusement.
