### ISSUE TITLE
[Bug] Drawer

### ISSUE THREAD

**Issue by SwouitAzia** [Paladium-Developpement/Paladium-Bedrock-Issues#67]
### Minecraft Username

Useless

### Description of the bug

Le drawer met pas + de temps à casser qu'avec une hache alors qu'il est en bois. 
Le test s'est effectué avec une hache en pierre.

**Comment by natof** [comment]
Minecraft n'offre pas la possibilité de définir une durabilité réelle pour les blocs. Ainsi, le seul moyen de casser des blocs moddés plus efficacement est d'utiliser un outil moddé.
