### ISSUE TITLE
[Bug] Objet/Armure en pala vert manquant

### ISSUE THREAD

**Issue by Anthogeof** [Paladium-Developpement/Paladium-Bedrock-Issues#7]
### Minecraft Username

Anthogeof

### Description of the bug

![image](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/166720968/a7a9b69f-aac0-44b8-b908-2a2ffcdedcfe)

Les objets en paladium vert sont manquant sauf le bloc qui lui est présent

**Comment by Anthogeof** [comment]
![image1](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/166720968/e7cad364-fe16-4e4b-a168-4100616c7539)

**Comment by Chaika9** [comment]
Salut, pour le moment c'est normal, car le PalaMod n'est pas mis encore officiellement sur la Beta privée (comme indiqué dans la roadmap).
