### ISSUE TITLE
[Bug] Cumulation d'enchantement 

### ISSUE THREAD

**Issue by Katsun1236** [Paladium-Developpement/Paladium-Bedrock-Issues#71]
### Minecraft Username

Katsun1246

### Description of the bug

La cumulation d'enchantement sur une épée en titane à l'enclume est impossible ( + utilisation quand même de la durabilité de l'enclume)

**Comment by natof** [comment]
Il est impossible avec ce qui est offert de combiner les enchantements avec des items moddés. On doit attendre que Minecraft le permette
