### ISSUE TITLE
[Bug] Spike

### ISSUE THREAD

**Issue by SwouitAzia** [Paladium-Developpement/Paladium-Bedrock-Issues#77]
### Minecraft Username

Useless

### Description of the bug

Quand je craft un spike, initialement elle possède une texture item 2D.
Après l'avoir posé puis cassé elle reprend une texture item de model "inversée".
Il s'agit ici de 2 bugs, le premier étant que le spike passe d'une texture item 2D à une texture item model.
Et le second (peut être pas un bug) est que la texture item model est inversée.

**Comment by AngeDechue** [comment]
Il n'y a pas ce problème là avec les spike en fer
