### ISSUE TITLE
[Bug] Texture des bottes en Endium

### ISSUE THREAD

**Issue by NervoxNight** [Paladium-Developpement/Paladium-Bedrock-Issues#80]
### Minecraft Username

NervoxNight

### Description of the bug

Bug de texture au niveau du haut des jambes avec les bottes en endium. 
![image](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/70534885/916538cd-8b79-49e0-a69b-566ea8887301)

**Comment by natof** [comment]
C'est la texture de base des bottes. Elle se combine avec la texture du legging
