### ISSUE TITLE
[Bug] Noms d'items

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#81]
### Minecraft Username

Legzo09

### Description of the bug

**Dans le livre des crafts de la table de craft, le nom de plusieurs items moddés est buggé, et affiche le nom brut du block.**
![Inv1](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/f7d82b04-9e92-4659-8f88-0cd82fc4691d)
![Inv2](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/7630aa0f-6da2-45b5-b86c-8cd3d954bb1f)
![Inv3](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/03b2dbe5-08ae-4cf9-bda9-71e4d468bc02)

**Comment by Chaika9** [comment]
Ce souci est normal pour le moment.
