### ISSUE TITLE
[Bug] Doubles coffres modifiables dans le spawn

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#92]
### Minecraft Username

Legzo09

### Description of the bug

Lorsqu'on casse un double coffre qui est dans le spawn, WorldGuard place 2 coffres simples à la place. On peut donc modifier le spawn à certains endroits s'il y a des doubles coffres dans la structure.

https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/abbc7d01-7aa5-4895-82ae-6b702b5cbdf5

**Comment by AngeDechue** [comment]
Ce n'est qu'un bug graphique côté client

**Comment by Legz0** [comment]
Je viens de retester, et effectivement, tu as raison. J'avoue que je n'avais pas pensé à déco-reco pour vérifier ça !

**Comment by Legz0** [comment]
Oups
