### ISSUE TITLE
[Bug] Les wandering traders peuvent apparaître dans le spawn

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#94]
### Minecraft Username

Legzo09

### Description of the bug

L'apparition des wandering traders n'est pas bloquée dans le spawn. Ils peuvent y apparaître naturellement.
![Legzo - WanderingTraders](https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/0b3d76a8-3fc0-4968-9ff7-870bce16119d)

**Comment by AngeDechue** [comment]
Ca a déjà été remonté

**Comment by Legz0** [comment]
Oui

**Comment by Chaika9** [comment]
Je ferme l'issue vue qu'elle existe deja
