### ISSUE TITLE
[Bug] Perte de nourriture dans le spawn

### ISSUE THREAD

**Issue by Legz0** [Paladium-Developpement/Paladium-Bedrock-Issues#96]
### Minecraft Username

Legzo09

### Description of the bug

On perd naturellement de la saturation et de la nourriture, même si on est dans le spawn. On peut donc être à 0 de nourriture dans le spawn.

https://github.com/Paladium-Developpement/Paladium-Bedrock-Issues/assets/142099731/2d0146d9-1a7c-4861-b994-de03eb5082b9

**Comment by Chaika9** [comment]
Ceci n'ai pas un bug, c'est normal
