### ISSUE TITLE
[Bug] Fusion d'outils du palamod dans l'enclume

### ISSUE THREAD

**Issue by Eucratide** [Paladium-Developpement/Paladium-Bedrock-Issues#97]
### Minecraft Username

Eucratide

### Description of the bug

J'ai trouvé un bug lors de la fusion d'outils dans une enclume.
D'après mes observations, il est impossible de fusionner 2 items du palamod dans une enclume si le premier item n'a pas perdue de durabilité.
Je n'ai pas tester toutes les possibilité mais avec les essaies que j'ai fait, je pense que la durabilité est concerné dans ce bug. J'ai une vidéo du bug mais elle dépasse les 10MB donc n'hésitez pas a me mp sur discord pour l'avoir si besoin

**Comment by AngeDechue** [comment]
Tu peux mettre la vidéo sur youtube en non répertorié et partager le lien ici

**Comment by Eucratide** [comment]
https://youtu.be/4Japf1Q65kU

**Comment by Katsun1236** [comment]
De mémoire, c'était pas dû à l'enchantement ?

**Comment by Eucratide** [comment]
Nan je pense pas, 2 pelles efficiency et l'autre unbreaking sont censés se combiner. J'avais fait pas mal de test pour essayer de trouver la cause du problème et ça ne semble pas venir de l'enchantement. Après, j'ai pas testé avec d'autres enchantement, j'avais cramé tous mes lvl pour testé des trucs x)

**Comment by natof** [comment]
Malheureusement, c'est un bug côté Minecraft. Il faut attendre le patch de leur côté
